### ISSUE TITLE
Responder perguntas para Definir sistemas inteligentes

### ISSUE THREAD

**Issue by mifegui** [ClaraOMello/EasyCode#7]

**Comment by ClaraOMello** [comment]
1. O seu sistema será inteligentes? Qual a inteligência que o sistema terá?
2. Quais recursos e técnicas de sistemas Inteligentes serão implementados?
3. Quais são as proposições de valores que os mecanismos de inteligência trazem ao seu sistema?
4. O sistema terá aprendizado online (enquanto o sistema funciona) ou offline (base de conhecimento treinada previamente)?
5. Quais são as entradas e saídas do seus modelos de inteligência artificial?
6. Qual é o principal fornecedor de tecnologia de IA como Serviços que você irá adotar?
7. Quais são os Serviços desse fornecedor que serão utilizados (ex. machine learning, processamento de imagens, chatbot)

**Comment by ClaraOMello** [comment]
1. AI de recomendação
2. Azure - machine learning
3. Propor conteúdo relevante para a conversa entre os usuários
4. Online
5. Entradas: mensagens do chat e tópicos; Saída: a recomendação de um tópico
6. Azure
7. Machine Learning
